<?php

namespace Drupal\card;

use Drupal\Core\Routing\RouteMatchInterface;

interface CardRepositoryInterface {

  /**
   * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
   * @return array
   */
  public function getCardsFromRouteMatch(RouteMatchInterface $route_match);

  /**
   * @TODO Not sure where this should go. Perhaps it will be moved in the future.
   * Gets a string based on the raw parameters from a route match.
   *
   * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
   *
   * @return string
   */
  public static function generateParameterString($route_match);

  /**
   * Decodes a parameter string as generated by generateParameterString back to
   * an array.
   *
   * @param $parameter_string
   * @return array
   */
  public static function decodeParameterString($parameter_string);

  /**
   * Generate an array of contextual meta config to attach to a region.
   *
   * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
   * @param string $region
   *
   * @return array Renderable array for an attach link.
   */
  public function generateRegionAttachLink($route_match, $region);
}